[package]
name = "bug"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "=0.7.3", features = ["csr"] }
reactive_stores = "=0.1.5"
console_log = "1.0.0"
log = "0.4.24"
